export default {
  EMAIL_RECEIVING_EMAIL_ADDRESS: "EMAIL_RECEIVING_EMAIL_ADDRESS",
  S3_PREFIX_ATTACHMENT: "S3_PREFIX_ATTACHMENT",
  S3_PREFIX_RAW_EMAIL: "S3_PREFIX_RAW_EMAIL",
  S3_PREFIX_TEXT_DETECTION_RESULT: "S3_PREFIX_TEXT_DETECTION_RESULT"
};
